
# タグが push されると、リリースが作成します。

name: Publish

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    
    steps:

      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4
     
      # リリースの作成
      - name: Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          generate_release_notes: true

